version: "2"
services:
    mongo-database:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --port 27017 --bind_ip_all
        networks:
            - webappnetwork
    api:
        image: webapp-api
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on:
            - mongo-database
        networks:
            - webappnetwork
        build: ./api
        command: /wait-for-it.sh mongo-database:27017 -- npm start
    client:
        image: mhart/alpine-node:12.9.1
        restart: always
        ports:
            - "3000:3000"
        working_dir: /client/src/app
        volumes:
            - ./client:/client/src/app
            - /client/node_modules
        depends_on:
            - mongo-database
        networks:
            - webappnetwork
        build: ./client
        command: /wait-for-it.sh mongo-database:27017 -- npm start
networks:
    webappnetwork:
        driver: bridge